"""Added fair_odds column

Revision ID: 2c59762efb46
Revises: 
Create Date: 2023-10-10 09:31:45.756342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c59762efb46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('fair_odds', sa.String(), nullable=False))
    op.add_column('user_bet', sa.Column('fair_odds', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bet', 'fair_odds')
    op.drop_column('bets', 'fair_odds')
    # ### end Alembic commands ###
